create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  phone text,
  role text not null default 'Brand & community lead',
  region text not null default 'Global',
  api_key text,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  platform text not null,
  status text not null default 'Needs review' check (status in ('Needs review', 'Ready to publish')),
  score integer,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;

create policy "Users manage their own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "Users manage their own posts" on public.posts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
